# Generated by Django 6.0.4 on 2026-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_conversation_exchangeoffer_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='conversation',
            name='dormitory_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('private', 'Private (Marketplace)'), ('group', 'Dormitory Group'), ('admin', 'Admin Support')], default='private', max_length=10),
        ),
    ]
