# Generated by Django 6.0.4 on 2026-04-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_machine_last_updated_machine_location_machine_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='time_left',
        ),
        migrations.AddField(
            model_name='machine',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
