# Generated by Django 6.0.4 on 2026-04-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_machine_last_updated_remove_machine_time_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='dormitory',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='last_reported_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
