# Generated by Django 6.0.4 on 2026-04-22 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_machine_dormitory_machine_last_reported_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='api.product'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('private', 'Private Chat'), ('market', 'Marketplace'), ('group', 'Dormitory Group'), ('admin', 'Admin Support')], default='private', max_length=10),
        ),
    ]
