# Generated by Django 6.0.4 on 2026-04-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('private', 'Private Chat'), ('market', 'Marketplace'), ('group', 'Dormitory Group'), ('admin', 'Admin Support'), ('global', 'Global Chat')], default='private', max_length=10),
        ),
    ]
