# Generated by Django 6.0.4 on 2026-05-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_analyticsevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('books', 'Books'), ('household', 'Household'), ('food', 'Food/Groceries'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
