# Generated by Django 6.0.4 on 2026-05-21 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reported_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('books', 'Books'), ('clothing', 'Clothing'), ('appliances', 'Appliances'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
