# Generated by Django 6.0.5 on 2026-05-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_event_end_date_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='occupied_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
