# Generated by Django 6.0.5 on 2026-05-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_machine_occupied_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
