# Generated by Django 6.0.3 on 2026-03-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='location',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='updated_at',
        ),
    ]
